version: 0.2
environment_variables:
   plaintext:
    HUGO_VERSION: "0.76.2"
  
phases:
  
  install:
    runtime-versions:
         docker: 18
    commands:
        - cd /tmp
        - wget https://github.com/gohugoio/hugo/releases/download/v${HUGO_VERSION}/hugo_extended_${HUGO_VERSION}_Linux-64bit.tar.gz
        - tar -xvf hugo_extended_${HUGO_VERSION}_Linux-64bit.tar.gz
        - echo Descargando version hugo_extended_${HUGO_VERSION}_Linux-64bit.tar.gz
        - mv hugo /usr/bin/hugo
        - cd -
        - rm -rf /tmp/*hugo*
       
 
  build:
    commands:
        - rm -rf public
        - hugo
        - aws s3 sync public/ s3://s3-hugo/ --region us-east-1
              
  pre_build:
     commands:
        - echo pre-build complete - Joel - Hugo 
        
  post_build:
     commands:
        - echo Build completed - Joel - Hugo demo
        
